version: '3'
services:
  yt-server:
    image: mgering/ytserver
    build:
      context: .
    ports:
      - "8220:8220"
    volumes:
      - ytserver-data:/data:rw
      - ytserver-yt:/ytdl/yt:rw
      - ytserver-x:/ytdl/x:rw

volumes:
  ytserver-data:
  ytserver-yt:
  ytserver-x:
