version: '3'
services:
  yt-server:
    image: ytserver
    # environment:
    #   - SYMFONY__ENV__DOMAIN_NAME="http://localhost:8083"
    #   - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    ports:
      - "8220:8220"
#    volumes:
#      - /opt/wallabag/images:/var/www/wallabag/web/assets/images
